### ISSUE TITLE
error returned from database: permission denied to create extension "uuid-ossp"

### ISSUE THREAD

**Issue by musicformellons** [cschaible/actix-web-security-samples#2]
I get following error:

```
 !  ~/P/a/o/backend  cargo run                                                                                                                                                  1690ms  Sat May  1 18:57:18 2021
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/resource-server-sample`
Error: while executing migrations: error returned from database: permission denied to create extension "uuid-ossp"

Caused by:
    error returned from database: permission denied to create extension "uuid-ossp"
```

**Comment by cschaible** [comment]
Hi @musicformellons, thanks for reporting the issue!

I couldn't reproduce the problem so far. It might be related to the docker script problems you've report in #1.

Could you check whether the problem still exists after rebasing to the latest version and pulling the latest images?
* docker pull postgres (Image ID: 26c8bcd8b719, Version 13.2)
* docker pull dpage/pgadmin4 (Image ID: 048c641d6e64, Version 5.2)

If the problem still exist, could you share more information about your environment (OS, Docker-, Docker-Compose- and Postgres version)? 

Can you check in the pgadmin web ui (localhost:5433) whether the actix user exists with a sql statement like below? The user `postgres` should have the permission: `superuser` and `create database`. The user `actix` and `keycloak` shouldn't have a role.

```sql
SELECT usename AS role_name,
  CASE 
     WHEN usesuper AND usecreatedb THEN 
	   CAST('superuser, create database' AS pg_catalog.text)
     WHEN usesuper THEN 
	    CAST('superuser' AS pg_catalog.text)
     WHEN usecreatedb THEN 
	    CAST('create database' AS pg_catalog.text)
     ELSE 
	    CAST('' AS pg_catalog.text)
  END role_attributes
FROM pg_catalog.pg_user
ORDER BY role_name desc;
```

Regards, Christian

**Comment by musicformellons** [comment]
<img width="398" alt="Screen Shot 2021-05-02 at 20 40 38" src="https://user-images.githubusercontent.com/10334123/116823796-e6bc4e80-ab86-11eb-890c-da6b5d1224a0.png">
